# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Prod environment
variables:

  # Global
  ap_vm_image: ubuntu-20.04

  namespace: mlopslite98 #Note: A namespace with many characters will cause storage account creation to fail due to storage account names having a limit of 24 characters.
  postfix: b
  location: eastus

  environment: prod
  enable_aml_computecluster: true
  enable_aml_secure_workspace: true
  enable_monitoring: false

  # Azure DevOps
  ado_service_connection_rg: Azure-ARM-Prod
  ado_service_connection_aml_ws: Azure-ARM-Prod

  # DO NOT TOUCH

  # For pipeline reference
  resource_group: aml12062301rg
  aml_workspace: Azuremlws
  application_insights: azuremlws4811793498
  key_vault: azuremlws0900979278
  container_registry: Azuremlcr99
  storage_account: azuremlws6937724445

  # For terraform reference
  terraform_version: 0.14.7
  terraform_workingdir: infrastructure
  terraform_st_resource_group: rgazureml6937724462
  terraform_st_location: $(location)
  terraform_st_storage_account: st$(namespace)$(postfix)$(environment)tf
  terraform_st_container_name: default
  terraform_st_key: mlops-tab
